### ISSUE TITLE
Find package metadata in a raw github repository

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#125]
**Describe the Feature**
For situations where a github repository gets added into the container using ADD directive, find the package metadata for the github repository.

**Use Cases**
This is a typical Dockerfile use case

**Implementation Changes**
1. ADD and COPY need to be recognized
```
if ADD or COPY in created_by and layer != 0: 
    # go through list of possibilities`
```
2. List of possibilities: This requires a new addition to the command library for poking at a collection of files and folders
```
# checks for what kind of directory this is
checks:
  - git: "git remote"
  - rpm:
  - default:
git:
  name:
    host:
        # run this on the filesystem
        - "git remote -v" # or better yet to find this in the git metadata
   version:
     host:
        - "git log -n 1" # or find it in refs
  license:
     host:
        - "cat LICENSE*"
```
(Should we consider submodules and any licenses therein?) 
3. Implement first finding what kind of collection of files this is, then go through the methods to get the information.
