### ISSUE TITLE
Please add zypper from SUSE to the snippet.yml file

### ISSUE THREAD

**Issue by jloehel** [tern-tools/tern#693]
**Describe the Feature**
I am missing zypper in snippet.yml to analyze openSUSE/SLES images correctly. Could you please add this functionality.

**Use Cases**
Generating compliance reports for openSUSE or SLES based Docker images.

**Implementation Changes**
I am not sure if something additionally is necessary but something like this might be enough:
```
zypper:
  install: 'in'
  remove: 'rm'
  ignore:
    - 'clean'
  packages: 'rpm'
```
Zypper allows you to shorten the subcommand. Is it possible to add more than one value for install and remove?
```
zypper:
  install: 
  - 'in'
  - 'install'
  remove: 
  - 'rm'
  - 'remove'
  ignore:
    - 'clean'
  packages: 'rpm'
```
