### ISSUE TITLE
Find installed software from shell script

### ISSUE THREAD

**Issue by ForgetMe17** [tern-tools/tern#743]
**Description**
In pr #717 , we parse a shell script into statements. We need to fiter the install command and extact what will be installed in the command.

**To Do**
1. Filter the install command.
2. Find what is being installed by the install command.

**Background**
Previous work #682.

**Super Issues**
#521

**Comment by ForgetMe17** [comment]
For a case mentioned in #744 .
```
apt-get install --no-install-recommends --no-install-suggests -y gnupg1 ca-certificates # INSTALL ca-certificates
...
...
apt-get remove --purge --auto-remove -y ca-certificates # REMOVE ca-certificates
```
`ca-certificates` should NOT be in the installed package list.
Besides, we may need to add `remove` to the remove subcommands of `apt-get`:
```
apt-get:
  install:
    - 'install' # subcommand to install
  remove:
    - 'purge' # subcommand to remove a package
  ignore: # list of subcommands that don't add or remove packages
    - 'update'
  packages: 'dpkg' # refer to base.yml's method of collection
```
