### ISSUE TITLE
npm packages with copyright info

### ISSUE THREAD

**Issue by mzachar** [tern-tools/tern#957]
Hi,

I was using tern to scan some node based images and the json report was missing copyrights info for npm packages.

**Describe the Feature**
Include copyright text from npm packages if they provide it in more or less standardise way (license.md, copying, ... files)

**Implementation Changes**
I patched the command_lib/base.yml to include copyrights for the npm packages like this:

```
copyrights:
    invoke:
      1:
        container:
          - "npm list -g --json --long --depth=1000 > npm-global.json"
      2:
        host:
          - "paths=`jq -r '.. | objects | select(has(\"name\") and has(\"version\")) | .path // \"Unknown\" | ltrimstr(\"/\")' npm-global.json`"
          - "files=\"license license.md LICENSE LICENSE.md copying copying.md COPYING COPYING.md\""
          - "for p in $paths; do for f in $files; do if [ -f $p/$f ]; then cat $p/$f; break; fi done; echo \"LICF\"; done"
    delimiter: "LICF"
```

If you think this would be good to have I'm happy to create a pull request.
